apiVersion: apps/v1
kind: Deployment
metadata:
  name: egarrage-backend
  namespace: egarrage

spec:
  replicas: 1

  selector:
    matchLabels:
      app: egarrage-backend

  template:
    metadata:
      labels:
        app: egarrage-backend

    spec:
      containers:
        - name: backend

          image: 129898048758.dkr.ecr.ap-south-1.amazonaws.com/egarrage-backend:8cd5265bfe688874adf6ddd2f51c43de8ce6d43e

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

            - name: POSTGRES_HOST
              value: "egarrage-postgres.cx0ycw0auo40.ap-south-1.rds.amazonaws.com"

            - name: POSTGRES_PORT
              value: "5432"

            - name: POSTGRES_DB
              value: "egarrage_db"

            - name: POSTGRES_USER
              value: "egarrage_user"

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: egarrage-db-secret
                  key: POSTGRES_PASSWORD

          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20