apiVersion: v1
kind: Service
metadata:
  name: egarrage-frontend
  namespace: egarrage
spec:
  selector:
    app: egarrage-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer